### ISSUE TITLE
"Unable to write pid file: no such file or directory"

### ISSUE THREAD

**Issue by rworkman** [lxc/cgmanager#22] opened 2015-11-20 05:49 UTC
Using cgmanager-0.39, this occurs:

> root@liberty:~# cgmanager --daemon name=cgmanager
> root@liberty:~# cgmanager: Unable to write pid file: No such file or directory

I found https://github.com/lxc/cgmanager/issues/11 but that appears to have been fixed after 0.37, and I confirmed that the lines removed in that commit are indeed not present in 0.39, so it's unclear what's happening here. The cgmanager daemon **is** starting up:

> root@liberty:~# ps aux | grep [c]gmanager
> root     22472  0.0  0.0  15312   140 ?        S    23:41   0:00 cgmanager --daemon name=cgmanager

but no pidfile is showing up in /run.

I've searched through the 0.39 code and I don't even see that a pidfile location is defined anywhere, so I'm guessing that it somehow comes from libnih - however, it looks like that would be done with nih_main_set_pidfile() and that's not present anywhere in cgmanager code either, best I can tell. 

What am I missing here?

**Comment by rworkman** [comment] 2015-11-20 05:58
Adding a call to nih_main_set_pidfile() in cgmanager.c indeed fixes this, but again, I feel like I'm missing something here...

**Comment by rworkman** [comment] 2015-12-10 05:02
Per Serge's comment on the the above commit (in my forked repo), it seems that the real problem has been identified. libnih uses /var/run by default for the pidfile location so there doesn't seem to be a valid reason for this to fail. How I completely missed that while figuring out how to manually define a pidfile location with libnih, well, I don't know - that's what I get for tunnel vision, I suppose. :/

After a bit of playing around here, I think I know _what_ happened although I don't know _why_ -- it seems that libnih doesn't like it if /var/run is a symlink to /run ; however, it's fine with /var/run being a bind mount to /run. After making that change, there's no problem at all. 
Perhaps libnih should change that hardcoded rundir location to /run, but at this point, I guess it doesn't matter. Thanks for the response and sorry for the noise. 
You guys can close this or I'll close it after a bit more time to ensure all is well.

**Comment by smemsh** [comment] 2016-01-28 23:43
Where can I find "Serge's comment?" I can confirm this behavior, but it seems wrong to me to change debian's /var/run symlink to a bind mount; it would have to be done again and again for any new container that uses debian installation defaults, and it alters the basic filesystem provided by vendor.

**Comment by rworkman** [comment] 2016-01-29 01:10
Aw crap, I deleted my repo, which deleted the comment too.
For what it's worth, we ended up rebuilding libnih to use /run instead of /var/run for pid files with a simple sed to main.c:
sed -i 's,/var/run,/run,g' nih/main.c

**Comment by smemsh** [comment] 2016-01-29 06:34
I see now, this bug seems to be related to #11.  However I think this bug should possibly be reopened; I'll explain:

For me, doing a bind mount does not work.  Are you sure that it worked for you? Do you (like me) have a separate `/var`?

I can see from tracing, right after cgmanager calls clone(), the child does:

```
open("/var/run/.cgmanager.pid.tmp", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT
```

this is after `nih_main_daemonize()`. Now `ENOENT` cannot be returned with `O_CREAT` flag unless some path component does not exist.  So I think this is not a problem with symlink at all but instead different mount namespace within `cgmanager`.

Is it because of earlier call to `unshare(CLONE_NEWNS)` and `pivot_root()`? I just tried making a test program that runs in the same namespace, and does the exact same tmpfile open, and it works just fine.  But after starting `cgmanager`, its mount namespace only contains:

```
 $ sudo nsenter -m -t `pgrep cgmanager` findmnt -no target,fstype
/                                         ext4
|-/root                                   tmpfs
|-/proc                                   proc
`-/run                                    tmpfs
  `-/run/cgmanager/fs                     tmpfs
    |-/run/cgmanager/fs/blkio             cgroup
    |-/run/cgmanager/fs/cpu               cgroup
    |-/run/cgmanager/fs/cpuacct           cgroup
    |-/run/cgmanager/fs/cpuset            cgroup
    |-/run/cgmanager/fs/devices           cgroup
    |-/run/cgmanager/fs/freezer           cgroup
    |-/run/cgmanager/fs/net_cls           cgroup
    |-/run/cgmanager/fs/net_prio          cgroup
    |-/run/cgmanager/fs/perf_event        cgroup
    `-/run/cgmanager/fs/none,name=systemd cgroup
```

On my system `/var` is a separate mount point, so it has no contents at all inside cgmanager's namespace:

```
 $ sudo nsenter -m -t `pgrep cgmanager` ls /var | wc -l
0
```

So I think this cannot work unless `cgmanager` does the tmpfile before unshare/pivot, or does like your patch and explicitly sets the location to be in `/run`.  The bug should probably be reopened, unless I'm misunderstanding what's happening.

What I don't get is why using a bind mount instead of symlink would change anything for you (and indeed, it does not for me), because that would not survive the root pivot.  Even if your `/var` is on the same filesystem as `/` it shouldn't make a difference.  Actually, maybe if it was a symlink, it would actually work! because the root filesystem _is_ carried into the `cgmanager` root (`pivot_into_new_root()` binds `/`, `/proc` and `/run` into place before pivot)

**Comment by rworkman** [comment] 2016-01-30 16:18
All of my failure was on a real system (not in a container). No separate /var filesystem. 
I think the best solution at this point is to change libnih to use /run instead of /var/run though, even if there is a logic problem inside cgmanager.

**Comment by smemsh** [comment] 2016-01-30 19:15
Yes, the failure occurs on the real system that first starts the containers... the namespace changes I'm talking about are done by cgmanager during daemonization on the real host. And if that system has a separate `/var`, it will not work at all unless libnih has its pidfile location changed (either by changing its default, or by override in cgmanager like your patch did), because `/var` is not taken into cgmanager's root pivot (only `/`, `/proc`, and `/run` are retained by the pivot).

I agree that libnih should default to `/run` instead of `/var/run`, but it still uses `/var/run` on e.g. debian, and changing libnih will impact many other programs which don't do any root pivot and work fine as-is.  Since `/run` will always work for cgmanager, and it will still do the right thing if the libnih default is changed anyways (as you suggest), I believe cgmanager should still be changed to do the override.

**Comment by rworkman** [comment] 2016-01-30 19:26
Okay, I think I get what you're saying now - yeah, I'll reopen this and let's see what happens.

**Comment by smemsh** [comment] 2016-01-30 19:35
thanks, but it won't let me do a pull request on this issue with my fork, since I didn't open it.  If you want to pull the change (it's identical, I only changed "_PID" to "_PIDFILE" in the constants) and resubmit... or, I can open a new issue and reference this one.

**Comment by rworkman** [comment] 2016-01-30 19:51
If you put something like "This fixes #22" in the commit message, it should get referenced from this issue when you do a PR on it. If that won't work, feel free to open a new issue. If you elect to try the edited commit message, feel free to add a Signed-off-by: line for me (but you don't have to).

**Comment by smemsh** [comment] 2016-01-30 20:40
I cannot do a PR on an issue I don't own, and it seems that a PR has to be attached to an issue.  When I made a PR, it just made a new issue #25.  I would have had to be added to this bug as an editor in order to attach it to this bug.

It does show the linkage here with just the commit, no PR (I included the "Closes #22" in my original commit message), it's just not in the form of a pull request, so upstream would have had to noticed this, and merge it manually, unless I made a new issue, or you did the PR.

I guess it made my PR into #25.  Too bad there is no way to do pull requests which address others' issues... sorry for the confusion.

**Comment by hallyn** [comment] 2016-02-04 05:51
On Sat, Jan 30, 2016 at 12:40:42PM -0800, Scott Mcdermott wrote:

> I cannot do a PR on an issue I don't own, and it seems that a PR has to be attached to an issue.  When I made a PR, it just made a new issue #25.  I would have had to be added to this bug as an editor in order to attach it to this bug.

Hi,

that sounds very much like a bug in github right now.  You certainly should be able to put 'Closes #22' in your commit message, and that should auto-close the issue when merged.

**Comment by hallyn** [comment] 2016-02-04 05:56
Looks like it got auto-closed - thanks again.

**Closed as completed** 2016-02-04 05:55 UTC

**Comment by rworkman** [comment] 2016-02-04 05:58
Thanks to both of you! :-)
