### ISSUE TITLE
Cgmanager breaks memory limits for containers with systemd

### ISSUE THREAD

**Issue by zazab** [lxc/cgmanager#10] opened 2015-06-24 03:43 UTC
Found weird behaviour: when cgmanager is running, memory restrictions for containers don't work. 
Any changes in mounting cgroups to container influence this behaviour, I try `lxc.mount.auto` with `cgroup:mixed`, `cgroup:ro` and `cgroup:rw`. With any value, it loose restrictions. Containers without systemd (tested with ubuntu 10.04) not affected. 
After some debug I found that problem is unsharing cgmanagers mounts (**fs.c:** _setup_cgroup_mounts()_). 
### How to reproduce:
1. Create lxc container with guest os using systemd,
2. Make shure there are some memory restrictions in lxc config, for example something like this: `lxc.cgroup.memory.limit_in_bytes = 4G`
3. Start container (but don't ssh into it),
4. Check containers cgroup memory.limit_in_bytes: `cat /sys/fs/cgroup/memory/lxc/container/memory.limit_in_bytes`, it would be 4G as we set.
5. ssh into container,
6. Check containers cgroup memory.limit_in_bytes again. There are no limits now.
7. Stop cgmanager
8. Restart container, and repeat steps 4-6, now restrictions doesn't change after ssh.
### Versions and other:

**Host OS:** Arch Linux (kernel 3.19.3-3-apparmor)
**Guest OS:** Arch Linux
**lxc version:** 1.0.6.61.ga44cafd-1  (also try 1.1.2.9.g17f48b9-1)
**cgmanager version:** 0.37-1
**full lxc config:**

```
# Config for container 'atest'
lxc.utsname = atest
lxc.rootfs = /var/lib/heaver/instances/abox.atest
lxc.aa_profile = lxc-container
lxc.console = /var/lib/lxc/atest/console

# mounts
lxc.mount.entry = /var/lib/heaver/instances/abox.atest/binds/dev /var/lib/heaver/instances/abox.atest/dev none bind 0 0
lxc.mount.entry = devpts /var/lib/heaver/instances/abox.atest/dev/pts devpts newinstance,ptmxmode=0666,nosuid,noexec 0 0
lxc.mount.auto = cgroup:mixed proc:mixed sys:rw

# net devices
lxc.network.type = veth
lxc.network.link = br0
lxc.network.name = eth0
lxc.network.flags = up
lxc.network.hwaddr = 2:85:c0:a8:97:35
lxc.network.ipv4 = 192.168.151.53/18
lxc.network.ipv4.gateway = 192.168.128.1


# limits
lxc.cgroup.cpu.cfs_period_us = 100000
lxc.cgroup.cpu.cfs_quota_us = 400000
lxc.cgroup.cpuset.cpus = 1,2,3
lxc.cgroup.memory.limit_in_bytes = 4G

# raw lxc config values
lxc.tty = 0
lxc.kmsg = 0
lxc.cgroup.devices.deny = a
lxc.cap.drop = sys_time
lxc.pts = 1024
lxc.cgroup.memory.oom_control = 1
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 4:0 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 10:200 rwm
lxc.cgroup.devices.allow = c 10:229 rwm
lxc.cgroup.devices.allow = c 254:0 rwm
```

**Comment by hallyn** [comment] 2015-06-24 20:37
I can't reproduce this here on ubuntu wily 3.19.0-22-generic.  can you show what memory.use_hierarchy shows?

**Comment by zazab** [comment] 2015-06-26 06:42
before ssh: `4294967296`
after ssh: `9223372036854771712` (the same value stored here if no limits is set)

**Comment by zazab** [comment] 2015-06-26 06:53
Tested with debian jessie as guest os. Not reproduced. But with archlinux guest, still loose restrictions.

**Comment by hallyn** [comment] 2015-06-26 16:04
On Thu, Jun 25, 2015 at 11:53:17PM -0700, Евгений Персиенко wrote:

> Tested with debian jessie as guest os. Not reproduced. But with archlinux guest, still loose restrictions.

Interesting - so this sounds like a bug in the arch linux kernel?  What were
the precise kernel versions in both tests?

**Comment by zazab** [comment] 2015-06-29 10:38
Problem not with **Host** Os or kernel. Problem is when **Guest** os is Arch linux. In both cases **Host** os and kernel is the same.

**Comment by hallyn** [comment] 2015-06-29 15:09
Ah, interesting.  Unfortunately arch isn't a download-available template.

Do you get the same results with a ubuntu wily container (which is
also systemd-based)/

**Comment by hallyn** [comment] 2015-10-23 04:47
(closing as out of date;   please re-open if requested info or new info is available)

**Closed as completed by hallyn** 2015-10-23 04:47 UTC
